repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: ^(.devcontainer/devcontainer.json|.vscode/extensions.json|.vscode/settings.json)$
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
